### ISSUE TITLE
a compile problem during compiling ygopro.

### ISSUE THREAD

**Issue by houranled** [Fluorohydride/ygopro#2037]
==== Building ocgcore (debug) ====
libcard.cpp
In file included from ../ocgcore/libcard.cpp:12:
../ocgcore/effect.h:25: error: expected ‘{’ before ‘;’ token
../ocgcore/effect.h:25: error: expected class-key before ‘;’ token
../ocgcore/effect.h:26: error: expected ‘{’ before ‘;’ token
../ocgcore/effect.h:26: error: expected class-key before ‘;’ token
make[1]: *** [../obj/Debug/ocgcore/libcard.o] Error 1
make: *** [ocgcore] Error 2

why?    How can i solve this problem?

**Comment by mercury233** [comment]
I guess you should update your gcc

**Comment by houranled** [comment]
@mercury233   
compiler version is here:

[root@houranlee 09:32:37]# gcc --version
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-18)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[root@houranlee 09:32:42]# g++ --version
g++ (GCC) 4.4.7 20120313 (Red Hat 4.4.7-18)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by mercury233** [comment]
I had encountered this problem before, and after updated gcc to 4.8 it is solved.

**Comment by zhykzhykzhyk** [comment]
At least gcc 4.6 for [enum forward declaration](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2008/n2764.pdf) which used in effect.h

**Comment by houranled** [comment]
after updating  gcc to 4.8,the last problem had been solved.But now it reported a new problem:

 In file included from ../gframe/client_card.h:4:0,
                 from ../gframe/client_card.cpp:1:
../gframe/config.h:50:22: fatal error: irrlicht.h: No such file or directory
 #include <irrlicht.h>
                      ^
compilation terminated

**Comment by mercury233** [comment]
https://github.com/Fluorohydride/ygopro/issues/2036

**Comment by houranled** [comment]
The url about irrlicht rpm package  have been changed...   

ATTENTION
======================================
The contents of this directory have been moved to our archives available at:

http://archives.fedoraproject.org/pub/archive/fedora/

If you are having troubles finding something there please stop by #fedora-admin on irc.freenode.net
